### ISSUE TITLE
安卓配置问题

### ISSUE THREAD

**Issue by ding-love-yu** [puti94/react-native-umeng-share#1]
# 1：
> //first
>     npm install react-native-puti-umeng-share --save
>     //then   android可自行导包，IOS由于静态库创建有问题，则需要手动集成
>     react-native link

**android可自行导包 这是什么意思呢？我不会原生开发有点搞不懂意思，是直接在项目的android目录下导入相关包还是在node_modules下面的react-native-puti-umeng-share里面导入包?望指点！**

# 2：
**readme下面的 【Android配置】我没搞懂到底是配置哪个文件？是项目下面的android项目下的AndroidManifest.xml文件么？**

# 3：

> //微信配置
在包名目录下创建wxapi文件夹，新建一个名为WXEntryActivity的activity继承WXCallbackActivity。
并配置Android Manifest XML

**请问这里的修改是在项目的android目录下修改，还是在node_modules下面的react-native-puti-umeng-share里面对应文件进行修改？并且WXCallbackActivity该文件在哪儿？并未看见？**

**Comment by puti94** [comment]
1：你执行react-native link android就会自己添加依赖了。
2：3，建议去了解下原生的一些基本的东西。所有修改都需要在RN项目下android文件下app里进行修改。需要用AndroidStudio进行操作

**Comment by puti94** [comment]
@ding-love-yu 
1：你执行react-native link android就会自己添加依赖了。
2：3，建议去了解下原生的一些基本的东西。所有修改都需要在RN项目下android文件下app里进行修改。需要用AndroidStudio进行操作

**Comment by ding-love-yu** [comment]
> @ding-love-yu
> 1：你执行react-native link android就会自己添加依赖了。

**
内容稍微有点多，忘作者百帮中仔细看一眼，真心希望获得您的帮助！感谢!我并非一来就问问题的，真心是这个搞了我几天了头都有点大了！！！
这个react-native link后就添加依赖了？我百度也是这么说的但是我没理解其意思 是就下载了相关文件的意思么？但是我并未在我的项目中发现相关文件的下载啊？我项目的安卓目录还是原来init时的样子我执行你link命令都是在windows的CMD下执行的，还是说必须要在android studio下的命令行执行才可?

另外：我之前才配置好一个社会化分享的插件, 他提供的源码是一个完整的RN项目， 我下载下来直接拷贝一些文件到我的项目中并做相应修改即能使用（不过过程有点曲折耗费了我一天时间），但是您提供的源码包似乎并非一个RN项目？我看目录结构似乎不一样，所以我找不到需要修改的配置文件。之前都是在RN项目下的安卓项目文件夹所做的修改，包括下载的库文件都是放在那里面的。

难道是我link的方式错误了么？我是一个web开发人员对原生不是很了解，但是我认为我并不是做原生开发
不应该止步于不会配置第三方插件就放弃这个好用的RN框架！希望作者不吝赐教！！！我也会帮助推荐好的插件的同时也希望帮助到其他的人！！！
**

**Comment by ding-love-yu** [comment]
![image](https://user-images.githubusercontent.com/16078611/33526049-7424b16a-d875-11e7-9064-e45d9b7ae1e8.png)
这个是我新init的一个项目
我按照您的步骤
1：npm install react-native-puti-umeng-share --save
2：react-native link
但是我的android的目录并没有什么变化，只是在node_modules目录多了一个react-native-puti-umeng-share模块，而这个模块我看就是您提供的源码吧？所以我才再第一次问题中请教到底是在android目录做配置的修改（我觉得应该是在此，之前的一个插件我就是在这里改的，但是这次里面的文件还是初始化之后的文件我找不到您说的几个文件比如：您提到的WXCallbackActivity文件）还是在node_modules下面这个react-native-puti-umeng-share模块做修改？(这里一般都不会去修改吧！！！)
望作者不吝赐教！万分感谢!!!!!

**Comment by puti94** [comment]
@ding-love-yu 
WXCallbackActivity 这个文件是要自己生成的，用来接收微信的回调。微信的sdk一般都需要这个Activity。在项目包名下建立一个wxapi的包名,再建立这个类
![wx20171204-091904](https://user-images.githubusercontent.com/23306184/33532430-96a8fbe2-d8d4-11e7-9637-658572736bd5.png)
然后在
![wx20171204-092409](https://user-images.githubusercontent.com/23306184/33532463-eb717a78-d8d4-11e7-8e6f-c597f9a16f3a.png)
添加这个Activity就行了
