### ISSUE TITLE
报了一个空指针错误

### ISSUE THREAD

**Issue by Chaunjie** [puti94/react-native-umeng-share#3]
我试用了你的插件，然后出现了一个空指针的错误
java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference @puti94

**Comment by puti94** [comment]
@Chaunjie 
你好，能把日志截图下来吗，就发了这一句话我是没办法定位问题的

**Comment by Chaunjie** [comment]
![image](https://user-images.githubusercontent.com/12093709/33523348-d6e45ed8-d7c9-11e7-83b7-598125fa3cdd.png)
@puti94

**Comment by puti94** [comment]
@Chaunjie 
这个问题我倒是没见过。最好把涉及到的代码都截图下来，我不知道是你集成步骤错了，还是调用错了，还是我的插件有问题，你应该懂andorid原生吧？

**Comment by Chaunjie** [comment]
@puti94 懂一点，方便加个qq吗？

**Comment by puti94** [comment]
如果出现此错误。是由于RN版本不同的原因。进入我的android源代码，如果是较早版本，是需要重写此方法的
![27f4bc7cd014a0eaa8ce5603d72c0295](https://user-images.githubusercontent.com/23306184/33532543-8946505c-d8d5-11e7-886f-9a2e446449a6.jpg)
